# Generated by Django 3.1.4 on 2024-08-02 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20240802_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Certificates',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='Deadline',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
