# Generated by Django 5.1 on 2024-08-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_blog_author_blog_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="youtube_id",
            field=models.CharField(max_length=200),
        ),
    ]
