# Generated by Django 3.1.4 on 2024-08-02 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20240802_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Certificates',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
