# Generated by Django 4.2.1 on 2024-08-07 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_usercourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='thumbnail',
        ),
    ]
