# Generated by Django 4.2.1 on 2024-08-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_video_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='youtube_id',
            field=models.IntegerField(max_length=200),
        ),
    ]
