# Generated by Django 4.2.1 on 2024-08-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_payment_course_alter_payment_user_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourse',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='paid',
            field=models.BooleanField(default=0, null=True),
        ),
    ]
